services:
  db:
    image: postgres:15-alpine
    container_name: django_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} --host=${POSTGRES_HOST:-db} --port=${POSTGRES_PORT:-5432}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: django_web
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-123123}@db:5432/${POSTGRES_DB:-mydb}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./project8sem:/app/project8sem
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             echo '--------------------------------------------------' &&
             echo 'Django development server is running at:' &&
             echo 'http://localhost:8000/' &&
             echo '--------------------------------------------------' &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data: